### ISSUE TITLE
Invalid API Key error on starting

### ISSUE THREAD

**Issue by ExpandingMan** [zulip/zulip-terminal#526]
On starting `zulip-term`, I get the following error immediately after entering my credentials:
```
Generated API key saved at /home/expandingman/zuliprc
Welcome to Zulip.
Loading |Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-4:
Traceback (most recent call last):
    self.run()
Invalid API key
  File "/usr/lib/python3.8/threading.py", line 870, in run
Exception in thread Thread-5:
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/site-packages/zulipterminal/core.py", line 253, in register_initial_desired_events
    self.run()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
    response = self.client.register(event_types=event_types)
  File "/usr/lib/python3.8/site-packages/zulip/__init__.py", line 752, in register
  File "/usr/lib/python3.8/threading.py", line 870, in run
  File "/usr/lib/python3.8/site-packages/zulipterminal/model.py", line 49, in _update_user_id
    self.run()
    self._target(*self._args, **self._kwargs)
    self.user_id = self.client.get_profile()['user_id']
Traceback (most recent call last):
    return self.call_endpoint(
  File "/usr/lib/python3.8/site-packages/zulip/__init__.py", line 618, in call_endpoint
  File "/usr/lib/python3.8/site-packages/zulip/__init__.py", line 783, in get_profile
  File "/usr/lib/python3.8/site-packages/zulipterminal/model.py", line 124, in get_messages
  File "/usr/lib/python3.8/threading.py", line 870, in run
    return self.do_api_query(marshalled_request, versioned_url, method=method,
  File "/usr/lib/python3.8/site-packages/zulipterminal/model.py", line 143, in _update_initial_data
    result = self.client.register(
    response = self.client.do_api_query(request, '/json/messages',
    return self.call_endpoint(
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/site-packages/zulipterminal/model.py", line 52, in _update_realm_users
  File "/usr/lib/python3.8/site-packages/zulip/__init__.py", line 501, in do_api_query
  File "/usr/lib/python3.8/site-packages/zulip/__init__.py", line 752, in register
    return self.call_endpoint(
  File "/usr/lib/python3.8/site-packages/zulip/__init__.py", line 501, in do_api_query
  File "/usr/lib/python3.8/site-packages/zulip/__init__.py", line 618, in call_endpoint
    return self.do_api_query(marshalled_request, versioned_url, method=method,
    self.ensure_session()
  File "/usr/lib/python3.8/site-packages/zulip/__init__.py", line 501, in do_api_query
    self.ensure_session()
    self.initial_data['realm_users'] = self.client.get_members(
  File "/usr/lib/python3.8/site-packages/zulip/__init__.py", line 818, in get_members
    self.ensure_session()
  File "/usr/lib/python3.8/site-packages/zulip/__init__.py", line 447, in ensure_session
    session.headers.update({"User-agent": self.get_user_agent()})
  File "/usr/lib/python3.8/site-packages/zulip/__init__.py", line 463, in get_user_agent
    vendor, vendor_version, dummy = platform.linux_distribution()
  File "/usr/lib/python3.8/site-packages/zulip/__init__.py", line 447, in ensure_session
  File "/usr/lib/python3.8/site-packages/zulip/__init__.py", line 447, in ensure_session
    return self.call_endpoint(
  File "/usr/lib/python3.8/site-packages/zulip/__init__.py", line 618, in call_endpoint
AttributeError: module 'platform' has no attribute 'linux_distribution'
    session.headers.update({"User-agent": self.get_user_agent()})
  File "/usr/lib/python3.8/site-packages/zulip/__init__.py", line 618, in call_endpoint
    session.headers.update({"User-agent": self.get_user_agent()})

During handling of the above exception, another exception occurred:

  File "/usr/lib/python3.8/site-packages/zulip/__init__.py", line 463, in get_user_agent
    return self.do_api_query(marshalled_request, versioned_url, method=method,
  File "/usr/lib/python3.8/site-packages/zulip/__init__.py", line 463, in get_user_agent
  File "/usr/lib/python3.8/site-packages/zulip/__init__.py", line 501, in do_api_query
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/zulipterminal/cli/run.py", line 123, in main
    Controller(zuliprc_path, zterm['theme']).main()
    return self.do_api_query(marshalled_request, versioned_url, method=method,
  File "/usr/lib/python3.8/site-packages/zulip/__init__.py", line 501, in do_api_query
    vendor, vendor_version, dummy = platform.linux_distribution()
AttributeError: module 'platform' has no attribute 'linux_distribution'
  File "/usr/lib/python3.8/site-packages/zulipterminal/core.py", line 30, in __init__
    self.model = Model(self)
  File "/usr/lib/python3.8/site-packages/zulipterminal/model.py", line 40, in __init__
    self._update_initial_data()
    self.ensure_session()
    vendor, vendor_version, dummy = platform.linux_distribution()
AttributeError: module 'platform' has no attribute 'linux_distribution'
    self.ensure_session()
  File "/usr/lib/python3.8/site-packages/zulip/__init__.py", line 447, in ensure_session
  File "/usr/lib/python3.8/site-packages/zulipterminal/model.py", line 159, in _update_initial_data
    raise urwid.ExitMainLoop()
urwid.main_loop.ExitMainLoop
Zulip Terminal has crashed!
  File "/usr/lib/python3.8/site-packages/zulip/__init__.py", line 447, in ensure_session
You can ask for help at:
https://chat.zulip.org/#narrow/stream/206-zulip-terminal

Thanks for using the Zulip-Terminal interface.

    session.headers.update({"User-agent": self.get_user_agent()})
  File "/usr/lib/python3.8/site-packages/zulip/__init__.py", line 463, in get_user_agent
    session.headers.update({"User-agent": self.get_user_agent()})
  File "/usr/lib/python3.8/site-packages/zulip/__init__.py", line 463, in get_user_agent
    vendor, vendor_version, dummy = platform.linux_distribution()
AttributeError: module 'platform' has no attribute 'linux_distribution'
    vendor, vendor_version, dummy = platform.linux_distribution()
AttributeError: module 'platform' has no attribute 'linux_distribution'
```

**Comment by neiljp** [comment]
@ExpandingMan Which version are you running?

**Comment by ExpandingMan** [comment]
Happened to try it on a different machine and didn't get an exception.  Will try to check what's different when I get a chance and let you know.

*Awesome* program by the way!  So cool to have a terminal version available.

**Comment by neiljp** [comment]
@ExpandingMan Glad you like it. This bug looks a little like a python3.8 issue we had, but it should have been fixed in the latest git version, hence my question on version :)

**Comment by ExpandingMan** [comment]
Yeah, it's the latest version of `zulip-term` that is fetched by `pip` in both cases, but it's crashing on Python 3.8 and working on Python 3.7.

**Comment by neiljp** [comment]
When you say 'fetched by `pip`', I assume you mean a `pip install zulip-term`? That should install version 0.4.0.

You *might* be able to fix this issue by manually upgrading the `zulip` package to the latest version, since that was where the python 3.8 issue was present.

The current version of git master is 133 commits ahead of 0.4.0, so may automatically resolve this issue, if you use that instead for now. It also has a lot of other features and enhancements.

Please let us know if you manage to resolve the problem.

**Comment by ExpandingMan** [comment]
Yes, it's the version fetched from `pip`, but I've yet to run the latest version.

**Comment by neiljp** [comment]
@ExpandingMan Thanks for letting us know. If you do run the version from git and confirm this is no longer an issue then we'd love to hear about it :)

**Comment by stratosgear** [comment]
Same issue running with python 3.8 from an arch box.

What is the easiest way to install latest version (>0.4.0) without recreating the whole development environment?

Thanks!

**Comment by neiljp** [comment]
@stratosgear You could try `pip3 install git+http://github.com/zulip/zulip-terminal.git@master`, which should install a snapshot of the current master.

**Comment by dmig-alarstudios** [comment]
@neiljp requirements are broken:
```
$ pip3 install git+http://github.com/zulip/zulip-terminal.git@master
Collecting git+http://github.com/zulip/zulip-terminal.git@master
  Cloning http://github.com/zulip/zulip-terminal.git (to revision master) to /tmp/pip-req-build-n6jpq13q
  Running command git clone -q http://github.com/zulip/zulip-terminal.git /tmp/pip-req-build-n6jpq13q
ERROR: Package 'zulip-term' requires a different Python: 3.8.2 not in '>=3.5, <=3.8'
```

**Comment by neiljp** [comment]
@dmig-alarstudios Just fixed in master in e3f9014f6. The next release will have this support too.

**Comment by neiljp** [comment]
This should be fixed not just in master, but also in the just-released 0.5.0 release, now available on PyPI.
